# Generated by Django 3.0.7 on 2024-06-14 21:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id_demande', models.AutoField(primary_key=True, serialize=False)),
                ('etat', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('complete', 'Complétée'), ('rejete', 'Rejetée')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'demande',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id_document', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='Hierarchie',
            fields=[
                ('id_hierarchie', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'hierarchie',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_service', models.AutoField(primary_key=True, serialize=False)),
                ('nom_service', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=50)),
                ('currency', models.CharField(default='Ariary', max_length=20)),
                ('documents_requis', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hierarchie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.Hierarchie')),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='HierarchieAuxiliaire',
            fields=[
                ('id_hierarchie', models.AutoField(primary_key=True, serialize=False)),
                ('code_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('arrondissement', models.CharField(blank=True, max_length=100, null=True)),
                ('hierarchie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hierarchie_domaine', to='services.Hierarchie')),
            ],
            options={
                'db_table': 'hierarchieauxiliaire',
            },
        ),
    ]
