# Generated by Django 3.0.7 on 2024-06-15 00:31

import apps.services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20240615_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='last_modification',
            field=models.DateTimeField(default=apps.services.models.default_created_at),
        ),
    ]
